2019-10-07 13:37:39,802 ERROR: Exception on /products/7 [GET] [in /home/matrizaev/cabinet/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/matrizaev/cabinet/app/routes.py", line 32, in ShowProducts
    return render_template('products.html', menuItem = 2, products = products, category = category)
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/matrizaev/cabinet/app/templates/products.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/matrizaev/cabinet/app/templates/base.html", line 87, in top-level template code
    {% block content %}{% endblock %}
  File "/home/matrizaev/cabinet/app/templates/products.html", line 44, in block "content"
    {{ form.id(class_ = 'd-none', hidden='') }}
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2019-10-07 13:38:46,344 INFO: Cabinet startup [in /home/matrizaev/cabinet/app/__init__.py:53]
2019-10-07 13:50:11,318 INFO: Cabinet startup [in /home/matrizaev/cabinet/app/__init__.py:53]
2019-10-07 13:50:15,310 ERROR: Exception on /products/7 [GET] [in /home/matrizaev/cabinet/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/matrizaev/cabinet/app/routes.py", line 33, in ShowProducts
    return render_template('products.html', menuItem = 2, products = products, category = category, form = form)
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/matrizaev/cabinet/app/templates/products.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/matrizaev/cabinet/app/templates/base.html", line 100, in top-level template code
    {% block content %}{% endblock %}
  File "/home/matrizaev/cabinet/app/templates/products.html", line 59, in block "content"
    url = "{{ url_for(UpdateProductPrice) }}"
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/flask/helpers.py", line 318, in url_for
    if endpoint[:1] == ".":
jinja2.exceptions.UndefinedError: 'UpdateProductPrice' is undefined
2019-10-07 13:51:11,093 INFO: Cabinet startup [in /home/matrizaev/cabinet/app/__init__.py:53]
2019-10-07 13:51:54,740 INFO: Cabinet startup [in /home/matrizaev/cabinet/app/__init__.py:53]
2019-10-07 13:52:32,639 INFO: Cabinet startup [in /home/matrizaev/cabinet/app/__init__.py:53]
2019-10-07 13:54:00,387 INFO: Cabinet startup [in /home/matrizaev/cabinet/app/__init__.py:53]
2019-10-07 13:56:16,960 INFO: Cabinet startup [in /home/matrizaev/cabinet/app/__init__.py:53]
2019-10-07 13:57:35,411 INFO: Cabinet startup [in /home/matrizaev/cabinet/app/__init__.py:53]
2019-10-07 13:58:02,426 INFO: Cabinet startup [in /home/matrizaev/cabinet/app/__init__.py:53]
2019-10-07 14:05:37,691 INFO: Cabinet startup [in /home/matrizaev/cabinet/app/__init__.py:53]
2019-10-07 14:06:24,301 INFO: Cabinet startup [in /home/matrizaev/cabinet/app/__init__.py:53]
2019-10-07 14:07:17,493 INFO: Cabinet startup [in /home/matrizaev/cabinet/app/__init__.py:53]
2019-10-07 14:58:23,897 INFO: Cabinet startup [in /home/matrizaev/cabinet/app/__init__.py:53]
2019-10-08 06:42:02,683 INFO: Cabinet startup [in /home/matrizaev/cabinet/app/__init__.py:53]
2019-10-08 06:42:16,352 INFO: Cabinet startup [in /home/matrizaev/cabinet/app/__init__.py:53]
2019-10-08 06:43:28,612 INFO: Cabinet startup [in /home/matrizaev/cabinet/app/__init__.py:53]
2019-10-08 06:45:21,169 INFO: Cabinet startup [in /home/matrizaev/cabinet/app/__init__.py:53]
2019-10-08 06:46:23,548 INFO: Cabinet startup [in /home/matrizaev/cabinet/app/__init__.py:53]
2019-10-08 06:46:33,049 ERROR: Exception on /update_price/ [POST] [in /home/matrizaev/cabinet/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/matrizaev/cabinet/app/routes.py", line 137, in UpdateProductPrice
    product = Product.query.filter (Product.id == form.data.id, Product.price == float(form.data.price), Product.store_id == current_user.id)
AttributeError: 'dict' object has no attribute 'id'
2019-10-08 06:48:21,844 INFO: Cabinet startup [in /home/matrizaev/cabinet/app/__init__.py:53]
