2019-10-29 11:11:56,731 ERROR: Exception on /remove_order/ [POST] [in /home/matrizaev/cabinet/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/matrizaev/cabinet/app/main/routes.py", line 126, in RemoveOrder
    order = Order.query.filter(Order.store_id == current_user.id, Order.id == form.data.id).first()
AttributeError: 'dict' object has no attribute 'id'
2019-10-29 11:12:27,528 INFO: Cabinet startup [in /home/matrizaev/cabinet/app/__init__.py:75]
2019-10-29 11:13:21,305 INFO: Cabinet startup [in /home/matrizaev/cabinet/app/__init__.py:75]
2019-10-29 11:15:38,233 INFO: Cabinet startup [in /home/matrizaev/cabinet/app/__init__.py:75]
2019-10-29 14:50:48,292 INFO: Cabinet startup [in /home/matrizaev/cabinet/app/__init__.py:75]
